name: Deploy to GCP VM

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH access to the GCP VM
      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      # Step 3: Deploy application on GCP VM
      - name: Deploy to GCP VM
        env:
          GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
        run: |
          ssh -i private_key.pem user@$GCP_VM_IP <<EOF
          set -e

          echo "Navigating to application directory..."
          cd /path/to/your/repo

          echo "Pulling latest changes..."
          git pull origin main

          echo "Rebuilding Docker containers..."
          docker-compose down
          docker-compose up -d --build

          echo "Deployment complete!"
          EOF
