name: Authenticate with GCP and Update Instance

on:
  push:
    branches:
      - main

jobs:
  gcloud-auth:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud Authentication
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Install gcloud CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates gnupg
        echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install -y google-cloud-cli

    - name: Configure gcloud CLI
      run: |
        gcloud config set project test-automation-445606
        gcloud config set compute/zone us-central1-a

    - name: Verify Authentication
      run: gcloud compute instances list

    - name: Update Instance with New Changes
      run: |
        gcloud compute ssh instance-20241229-124431 \
          --zone us-central1-a \
          --command "
            sudo su -c 'ls -l / && \
            cd /automation/ && \
            ls -l && \
            git pull && \
            docker build -t client-end . && \
            docker stop client-end-container || true && \
            docker rm client-end-container || true && \
            docker run -d --name client-end-container client-end'
          "
