name: Authenticate with GCP

on:
  push:
    branches:
      - main

jobs:
  gcloud-auth:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install gcloud CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates gnupg
        echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install -y google-cloud-cli

    - name: Authenticate to GCP
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > gcloud-key.json
        cat gcloud-key.json # Optional: Verify the JSON structure in logs (for debugging)
        gcloud auth activate-service-account --key-file=gcloud-key.json
        gcloud config set project test-automation-445606
        gcloud config set compute/zone us-central1-a

    - name: Verify Authentication
      run: gcloud compute instances list
