name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > sa-key.json
          gcloud auth activate-service-account --key-file=sa-key.json
          gcloud config set project YOUR_PROJECT_ID

      # Step 3: Deploy to GCP VM
      - name: Deploy application
        run: |
          echo "Connecting to GCP VM..."
          gcloud compute ssh pawarvaibhav.vppv@YOUR_INSTANCE_NAME \
            --zone=YOUR_INSTANCE_ZONE \
            --command="cd /path/to/your/repo && \
                       git pull origin main && \
                       docker-compose down && \
                       docker-compose up -d --build"

      # Step 4: Clean up
      - name: Clean up
        run: |
          rm -f sa-key.json
